### ISSUE TITLE
Support .NET projects

### ISSUE THREAD

**Issue by savannahostrowski** [docker/copilot-issues#10]
Today, we support node, Java and node projects. We should expand support to cover .NET as well.

**Comment by timheuer** [comment]
Definitely would appreciate .NET support 💜 

Depending on models being used for the LLM, some fine-tuning/RAG approaches might be needed to suggest correct version usage (e.g., .NET 8 released after current model training so Copilot giving wrong answers), differences in images (e.g., SDK versus runtime), etc.

Initial uses with `@docker` Copilot was that in the simpler questions it mostly got it right sans correct version tags
