### ISSUE TITLE
Error Code: ABORT_ERR when using extension in VS Code

### ISSUE THREAD

**Issue by isaacrlevin** [docker/copilot-issues#40]
## Environment data

-   Client (e.g. github.com, VS Code, Codespaces, JetBrains): Visual Studio Code
-   Languages and versions: Empty Workspace
-   Other details: N/A

## Repro Steps

Ask a question using the @docker extension in the GitHub Copilot Chat extension in VS Code

## Expected behavior

Extension should answer the question, similar to when I do it in the GitHub website
![image](https://github.com/user-attachments/assets/be16ffaf-56a4-42fe-8600-d5c903425e30)

## Actual behavior

I get this message
![image](https://github.com/user-attachments/assets/62226a1a-cc24-4ee3-ada4-c609504fc4d2)

**Comment by savannahostrowski** [comment]
Hey @isaacrlevin thanks for the report. After digging into this, it looks like error is actually from the Copilot Chat extension or Copilot itself. I've shared this report with our contacts over at GitHub around possibly enhancing the user experience here for clarity.

**Comment by savannahostrowski** [comment]
@isaacrlevin Would you mind sharing if you were using VS Code stable or insiders? Also, which version?

**Comment by isaacrlevin** [comment]
VS Code Insiders

Version: 1.93.0-insider (system setup)
Commit: d751e4324d12370e950f8cd031aa8829637ce300
Date: 2024-08-16T05:03:54.591Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by savannahostrowski** [comment]
This was confirmed to be a VS Code issue. The GitHub team is working on a fix. Thanks for reporting!
