### ISSUE TITLE
Docker for GitHub Copilot data retention policy

### ISSUE THREAD

**Issue by fortmate** [docker/copilot-issues#41]
Hi, Thank you very much for your work.
I want to know how much your GitHub Copilot's extentions "Docker for GitHub Copilot" uses our repository's data.
I don't want our data to get breached, but I couldn't find  any descriptions for the data retention or processing policy.
Is the input processed and deleted immediately after replying?
Is the data securely transferred between GitHub and Docker?
If the data is processed solely within GitHub, that's the best.
If not, I want to know how to securely use your extentions.

Thank you for your dedication.

**Comment by savannahostrowski** [comment]
Hey there - thanks for the question.

Docker's treatment of its customers and users data is detailed at and accessible at our Privacy page at https://www.docker.com/legal/privacy/. Therein you can find our Data Privacy Policy as well our Data Processing Addendum. 

If you have remaining queries, you can email [privacy@docker.com](mailto:privacy@docker.com)
