### ISSUE TITLE
https://github.com/docker/copilot-issues.git

### ISSUE THREAD

**Issue by SOKCHIN34** [docker/copilot-issues#43]
**HBIE

## Environment data

-   Client (e.g. github.com, VS Code, Codespaces, JetBrains):
-   Languages and versions: XXX
-   Other details: XXX

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

**Comment by krissetto** [comment]
please add some info before opening an issue if you're having problems.
