### ISSUE TITLE
123

### ISSUE THREAD

**Issue by SOKCHIN34** [docker/copilot-issues#44]
## Environment data

-   Client (e.g. github.com, VS Code, Codespaces, JetBrains):
-   Languages and versions: XXX
-   Other details: XXX

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

**Comment by SOKCHIN34** [comment]
![Screenshot_20240902-220032](https://github.com/user-attachments/assets/8eca28e5-54ce-4205-8a9e-c75c46d0f68f)
Ok

**Comment by SOKCHIN34** [comment]
Yes
Ok
Good

**Comment by Benehiko** [comment]
Yes
Ok
Good
